# roles/sqlite/defaults/main.yml
---
sqlite_directory: /var/mail/sqlite
sqlite_databases: [authdb]
authdb_email: 'postmaster'
authdb_alias: 'info'
authdb_userid: 'info'
authdb_domain: 'server.com'
authdb_password: ''
...
